
'use server';

import { faker } from '@faker-js/faker';
import { CharacterClass as CharacterClassEnum, type Skill } from '@/ai/schemas';
import {
  type SkillName,
  type SkillLevel,
  skillCatalog,
} from '@/lib/skills';
import type { Character } from '@/lib/types';
import { randomBytes } from 'crypto';


// The return type should not have description or backstory, as they are generated by AI later.
export type CharacterGenerationResult = Omit<Character, 'description' | 'backstory' | 'playerId'>;

// DATA TABLES
const trinkets = [
    "A dog-eared paperback of a trashy sci-fi romance novel.",
    "A small, worn plushie of a six-legged creature.",
    "A single, perfectly preserved iridescent beetle wing.",
    "A necklace made of spent shell casings.",
    "A datachip containing a single, looping, melancholic song.",
    "A heavily-redacted printout of a corporate incident report.",
    "A small, intricately carved wooden bird.",
    "A photo of a stranger, with 'Forgive Me' written on the back.",
    "A tarnished silver locket, empty inside.",
    "A pair of loaded dice.",
    "A deck of playing cards with strange, alien-like suits.",
    "A single, antique key to an unknown lock.",
    "A vial of luminescent blue fluid that hums faintly.",
    "A bundle of dried, alien herbs that smell of ozone.",
    "A smooth, grey stone that is always cool to the touch.",
    "A folded piece of paper with a complex, unfinished star chart.",
    "A corporate-branded stress ball, worn and cracked.",
    "A string of colorful beads from a forgotten culture.",
    "A child's drawing of a monster.",
    "A patch from a ship that was reported lost with all hands."
];

const patches = [
    "A patch that reads 'BIG MISTAKE'.",
    "A patch depicting a skull in a spacesuit.",
    "A patch that says 'I'm With Stupid' with an arrow pointing in a random direction.",
    "A patch for a ship that was decommissioned a decade ago.",
    "A corporate logo for a company that went bankrupt.",
    "A patch with a cartoon alien giving the middle finger.",
    "A patch that reads 'SPACE IS TRYING TO KILL ME'.",
    "A simple, black patch with a single, white tear drop.",
    "A patch depicting a flaming dumpster.",
    "A patch that reads 'DON'T FOLLOW ME, I'M LOST TOO'.",
    "A crudely drawn smiley face, spattered with what looks like dried blood.",
    "A patch that says 'WARNING: CONTENTS UNDER PRESSURE'.",
    "A patch with the name of a person, crossed out.",
    "A patch that reads 'FIRST IN, LAST OUT'.",
    "A patch depicting a planet cracking in half.",
    "A patch that says 'POWERED BY COFFEE AND SPITE'.",
    "A patch of a black cat with its back arched.",
    "A patch that reads 'MY OTHER RIDE IS A HEARSE'.",
    "A patch showing a schematic of a weapon that violates several treaties.",
    "A simple, red patch that reads 'SURVIVOR'."
];

const traumaResponses: Record<CharacterClassEnum, string> = {
    'Marine': 'WHENEVER YOU PANIC, EVERY CLOSE FRIENDLY PLAYER MUST MAKE A FEAR SAVE.',
    'Android': 'FEAR SAVES MADE BY CLOSE FRIENDLY PLAYERS ARE AT DISADVANTAGE.',
    'Scientist': 'WHENEVER YOU FAIL A SANITY SAVE, ALL CLOSE FRIENDLY PLAYERS GAIN 1 STRESS.',
    'Teamster': 'ONCE PER SESSION, YOU MAY TAKE ADVANTAGE ON A PANIC CHECK.'
};

// Helper function to generate a name based on class
const generateName = (charClass: CharacterClassEnum): string => {
    const firstName = faker.person.firstName();
    const lastName = faker.person.lastName();
    const hasNickname = Math.random() < 0.1; // 10% chance of a nickname
    const nickname = faker.person.middleName();

    switch (charClass) {
        case 'Scientist':
            if (hasNickname) {
                return `Dr. ${firstName} "${nickname}" ${lastName}`;
            }
            return `Dr. ${firstName} ${lastName}`;
        case 'Android':
            const prefix = faker.string.alpha({ length: 2, casing: 'upper' });
            const digits = faker.string.numeric(4);
            return `${prefix}-${digits}`;
        case 'Teamster':
        case 'Marine':
        default:
            if (hasNickname) {
                return `${firstName} "${nickname}" ${lastName}`;
            }
            return `${firstName} ${lastName}`;
    }
};

// Secure random number generation
const secureRandom = (max: number) => {
    return randomBytes(1).readUInt8(0) % max;
};

// Helper function to roll a d10
const rollD10 = () => secureRandom(10) + 1;


// Helper function to sum 2 d10 rolls
const roll2d10 = () => {
    return rollD10() + rollD10();
};

const getRandomClass = (): CharacterClassEnum => {
    const classes: CharacterClassEnum[] = ['Teamster', 'Marine', 'Scientist', 'Android'];
    return classes[secureRandom(classes.length)];
};


// Helper to add a skill if not already present, and recursively add its prerequisites
const addSkillAndPrerequisites = (skillSet: Set<SkillName>, skillName: SkillName) => {
    if (skillSet.has(skillName)) {
        return; // Skill already in the set
    }

    const skillDef = skillCatalog[skillName];
    if (!skillDef) return;

    // First, recursively add all prerequisites
    if (skillDef.prerequisites && skillDef.prerequisites.length > 0) {
        for (const prereqName of skillDef.prerequisites) {
            addSkillAndPrerequisites(skillSet, prereqName);
        }
    }
    // Then, add the skill itself
    skillSet.add(skillName);
};

// Helper to get a random skill that is not already in the list
const getRandomNewSkill = (currentSkillNames: Set<SkillName>, level: SkillLevel): SkillName => {
    const allSkillNames = Object.keys(skillCatalog) as SkillName[];
    
    let availableSkills = allSkillNames.filter(name => {
        const skillDef = skillCatalog[name];
        return skillDef.level === level && !currentSkillNames.has(name);
    });

    if (level === 'Expert' || level === 'Master') {
        availableSkills = availableSkills.filter(name => {
            const prereqs = skillCatalog[name].prerequisites;
            return prereqs.length > 0 && prereqs.every(prereq => currentSkillNames.has(prereq));
        });
    }

    if (availableSkills.length === 0) {
        const fallbackSkills = allSkillNames.filter(name => skillCatalog[name].level === 'Trained' && !currentSkillNames.has(name));
        if (fallbackSkills.length > 0) {
            return fallbackSkills[secureRandom(fallbackSkills.length)];
        }
        return 'Athletics';
    }
    
    return availableSkills[secureRandom(availableSkills.length)];
};


export async function createCharacter(playerClass?: CharacterClassEnum): Promise<CharacterGenerationResult> {
    const charClass = playerClass || getRandomClass();
    const characterId = faker.string.uuid();

    const startingHealth = rollD10() + 10;
    
    let maxWounds = 2; // Default for Teamster and Scientist
    if (charClass === 'Marine') maxWounds = 3;
    if (charClass === 'Android') maxWounds = 4;

    const inventory: string[] = [];
    let credits = (rollD10() + rollD10()) * 10;
    const skillNames = new Set<SkillName>();

    // Apply class-specific modifications & loadouts
    switch (charClass) {
        case 'Teamster':
            inventory.push(secureRandom(2) > 0 ? 'Wrench' : 'Shotgun');
            inventory.push('Flashlight', 'Toolkit', '6 Rations', 'Vaccsuit');
            break;
        case 'Scientist':
            inventory.push('Stun Baton', 'Data Pad', 'Sample Kit', '6 Rations', 'Vaccsuit');
            break;
        case 'Android':
            inventory.push(secureRandom(2) > 0 ? 'Scalpel' : 'Wrench');
            inventory.push('Toolkit');
            inventory.push(secureRandom(2) > 0 ? 'Wired Reflexes' : 'Interface Rig');
            inventory.push('Synthetic Skin', '6 Rations', 'Vaccsuit');
            credits = 0; // Androids start with 0 credits
            break;
        case 'Marine':
            inventory.push(secureRandom(2) > 0 ? 'Pulse Rifle' : 'SMG');
            inventory.push('Frag Grenade (x2)', 'Combat Armor', '6 Rations');
            break;
    }
    
    const modifiers = {
        stats: { strength: 0, speed: 0, intellect: 0, combat: 0 },
        saves: { sanity: 0, fear: 0, body: 0 },
    };

    // Apply class-specific stat/skill modifications
    switch (charClass) {
        case 'Teamster':
            modifiers.stats.strength += 5;
            modifiers.saves.body += 10;
            
            addSkillAndPrerequisites(skillNames, 'Industrial Equipment');
            addSkillAndPrerequisites(skillNames, 'Zero-G');
            
            const bonusTrainedTeamster = getRandomNewSkill(skillNames, 'Trained');
            addSkillAndPrerequisites(skillNames, bonusTrainedTeamster);
            const bonusExpertTeamster = getRandomNewSkill(skillNames, 'Expert');
            addSkillAndPrerequisites(skillNames, bonusExpertTeamster);
            break;
        case 'Marine':
            modifiers.stats.combat += 10;
            modifiers.saves.fear += 20;
            modifiers.saves.body += 10;


            addSkillAndPrerequisites(skillNames, 'Military Training');
            addSkillAndPrerequisites(skillNames, 'Athletics');
            
            if (secureRandom(2) > 0) {
                const bonusExpert = getRandomNewSkill(skillNames, 'Expert');
                addSkillAndPrerequisites(skillNames, bonusExpert);
            } else {
                const allTrainedSkills = (Object.keys(skillCatalog) as SkillName[]).filter(
                    name => skillCatalog[name].level === 'Trained' && !skillNames.has(name)
                );
                
                for (let i = allTrainedSkills.length - 1; i > 0; i--) {
                    const j = secureRandom(i + 1);
                    [allTrainedSkills[i], allTrainedSkills[j]] = [allTrainedSkills[j], allTrainedSkills[i]];
                }

                if(allTrainedSkills.length > 0) addSkillAndPrerequisites(skillNames, allTrainedSkills[0]);
                if(allTrainedSkills.length > 1) addSkillAndPrerequisites(skillNames, allTrainedSkills[1]);
            }
            break;
        case 'Scientist':
            modifiers.stats.intellect += 10;
            modifiers.saves.sanity += 30;
            const statsToBuff = ['strength', 'speed', 'intellect', 'combat'] as const;
            const statToBuff = statsToBuff[secureRandom(statsToBuff.length)];
            modifiers.stats[statToBuff] += 5;

            const masterSkills = (Object.keys(skillCatalog) as SkillName[]).filter(name => skillCatalog[name].level === 'Master');
            const masterSkillName = masterSkills[secureRandom(masterSkills.length)];
            addSkillAndPrerequisites(skillNames, masterSkillName);

            const bonusTrainedScientist = getRandomNewSkill(skillNames, 'Trained');
            addSkillAndPrerequisites(skillNames, bonusTrainedScientist);
            break;
        case 'Android':
            modifiers.stats.intellect += 20;
            modifiers.saves.fear += 60;
            const statsToDebuff = ['strength', 'speed', 'intellect', 'combat'] as const;
            const statToDebuff = statsToDebuff[secureRandom(statsToDebuff.length)];
            modifiers.stats[statToDebuff] -= 10;

            addSkillAndPrerequisites(skillNames, 'Linguistics');
            addSkillAndPrerequisites(skillNames, 'Computers');
            addSkillAndPrerequisites(skillNames, 'Mathematics');

            if (secureRandom(2) > 0) {
                const bonusExpert = getRandomNewSkill(skillNames, 'Expert');
                addSkillAndPrerequisites(skillNames, bonusExpert);
            } else {
                const bonusTrained1 = getRandomNewSkill(skillNames, 'Trained');
                addSkillAndPrerequisites(skillNames, bonusTrained1);
                const bonusTrained2 = getRandomNewSkill(skillNames, 'Trained');
                addSkillAndPrerequisites(skillNames, bonusTrained2);
            }
            break;
    }
    
    // Add some common gear if not already in a loadout
    if (!inventory.some(item => item.toLowerCase().includes('medpac') || item.toLowerCase().includes('first aid'))) {
        inventory.push('Standard-Issue Medpac');
    }
    if (!inventory.some(item => item.toLowerCase().includes('flashlight'))) {
        inventory.push('Flashlight');
    }
    
    // Add trinket and patch to the end of the list
    inventory.push(`Trinket: ${trinkets[secureRandom(trinkets.length)]}`);
    inventory.push(`Patch: ${patches[secureRandom(patches.length)]}`);

    const finalSkills: Skill[] = Array.from(skillNames).map(name => ({
        name: name,
        level: skillCatalog[name].level
    }));

    const character: CharacterGenerationResult = {
        id: characterId,
        name: generateName(charClass),
        class: charClass,
        credits: credits,
        highScore: 0,
        armorPoints: 0,
        traumaResponse: traumaResponses[charClass],
        stats: {
            strength: roll2d10() + 25,
            speed: roll2d10() + 25,
            intellect: roll2d10() + 25,
            combat: roll2d10() + 25,
        },
        saves: {
            sanity: roll2d10() + 10,
            fear: roll2d10() + 10,
            body: roll2d10() + 10,
        },
        modifiers,
        health: { current: startingHealth, max: startingHealth },
        stress: { current: charClass === 'Android' ? 0 : 2, min: charClass === 'Android' ? 0 : 2 },
        wounds: { current: 0, max: maxWounds },
        carryingCapacity: { current: 0, max: 0 },
        skills: finalSkills,
        inventory: inventory
    };

    return character;
}
